name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        neo4j_version:
          - "4.4"
          - "4.4-enterprise"
          - "5.6"
          - "5.6-enterprise"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Test
        env:
          NEO4J_VERSION: ${{ matrix.neo4j_version }}
        run: go test -v ./...
