name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        neo4j_version:
        - "4.3"
        - "4.3-enterprise"
        - "4.4"
        - "4.4-enterprise"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      env:
        NEO4J_VERSION: ${{ matrix.neo4j_version }}
      run: go test -v ./...
